package pert1;

class Pengguna {
    // Tuliskan state (variabel) yang diperlukan di sini
    // Jangan lupa tambahkan konstanta faktorAktivitas
    public double a,b;

    public Pengguna(double a, double b) {
        this.a = a;
        this.b = b;
    }

    double hitungBMI() {
        // Lengkapi method ini
        return a+b;
    }

//    void tampilKategori() {
//        // Lengkapi method ini
//    }

//    double hitungKalori() {
//        // Lengkapi method ini
//    }

//    void tampilInfo() {
//        // Lengkapi method ini
//    }
}